project:
  type: website

website:
  title: "Data Science and Statistics in R for Fellowship"
  repo-url: https://caius-gibeily.github.io/r4dss26/
  repo-actions: [edit, issue]
  repo-subdir: "docs"
  page-navigation: true
  sidebar:
    contents:
      - section: R for Data Science 2026-27
        contents:
          - intro.qmd
          - Session_1.qmd
          
theme:
  light: cosmo
  dark: darkly
